SBMS/SBMS/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SBMS.Model.Model;
using SBMS.BLL.BLL;
using SBMS.DatabaseContext.DatabaseContext;
using System.Data.Entity;


namespace SBMS.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetData()
        {
            using (SBMS_DBContext db = new SBMS_DBContext())
            {
                List<Customer> customerList = db.Customers.ToList<Customer>();
                return Json(new { data = customerList }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            //Customer customer = new Customer();

            if (id == 0)
            { return View(new Customer());}
                
            else
            {
                using (SBMS_DBContext db = new SBMS_DBContext())
                {
                    return View(db.Customers.Where(x => x.ClietId == id).FirstOrDefault<Customer>());
                }
            }
        }
        [HttpPost]
        public ActionResult AddOrEdit(Customer customer)
        {
            using (SBMS_DBContext db = new SBMS_DBContext())
            {
                if (customer.ClietId == 0)
                {
                    db.Customers.Add(customer);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    db.Entry(customer).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }


        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (SBMS_DBContext db = new SBMS_DBContext())
            {
                Customer customer = db.Customers.Where(x => x.ClietId == id).FirstOrDefault<Customer>();
                db.Customers.Remove(customer);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

SBMS/SBMS/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SBMS.Model.Model;
using SBMS.BLL.BLL;
using SBMS.DatabaseContext.DatabaseContext;
using System.Data.Entity;

namespace SBMS.Controllers
{
    public class ProductController : Controller
    {
       
        // GET: Product
        public ActionResult Index()
        {
           
            return View();
        }
        [HttpGet]
        public ActionResult GetData()
        {
            using (SBMS_DBContext db = new SBMS_DBContext())
            {
                List<Product> prodList = db.Products.ToList<Product>();

                return Json(new { data = prodList }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            Product product=new Product();


            if (id == 0)
                using (SBMS_DBContext db = new SBMS_DBContext())
                {
                    product.Categories = db.Categories.ToList<Category>();
                    return View(product);
                }
            else
            {
                using (SBMS_DBContext db = new SBMS_DBContext())
                {
                    product.Categories = db.Categories.ToList<Category>();
                    return View(db.Products.Where(x => x.Id == id).FirstOrDefault<Product>());
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(Product product)
        {
            using (SBMS_DBContext db = new SBMS_DBContext())
            {
                if (product.Id == 0)
                {
                    db.Products.Add(product);
                    db.SaveChanges();
                    return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                }
            }


        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            using (SBMS_DBContext db = new SBMS_DBContext())
            {
                Product product = db.Products.Where(x => x.Id == id).FirstOrDefault<Product>();
                db.Products.Remove(product);
                db.SaveChanges();
                return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
            }

        }

     
    }
}

SBMS/SBMS/Views/Customer/AddOrEdit.cshtml
@model SBMS.Model.Model.Customer
@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Customer", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.ClietId)
    <div class="form-group">
        @Html.LabelFor(model => model.CustomerName, new { @class = "control-label" })
        @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.CustomerName)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Address, new { @class = "control-label" })
        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Address)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email, new { @class = "control-label" })
        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Contact, new { @class = "control-label" })
        @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.LoyaltyPoint, new { @class = "control-label" })
        @Html.EditorFor(model => model.LoyaltyPoint, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ImagePath, new { @class = "control-label" })
        <input type="file" name="ImageFile" required>
    </div>

    
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
        <input type="reset" value="Reset" class="btn" />
    </div>
}

SBMS/SBMS/Views/Customer/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainDataLayout.cshtml";
}

<h2>Customer Details</h2>

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddOrEdit","Customer")')"><i class="fa fa-plus"></i> Add New</a>
<table id="customerTable" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>ClietId</th>
            <th>CustomerName</th>
            <th> Address</th>
            <th>Email</th>
            <th>Contact</th>
            <th>LoyaltyPoint</th>
            <th>ImagePath</th>
            <th></th>
        </tr>
    </thead>
</table>


<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
@section scripts{

<script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>

    <script>
        var Popup, dataTable;
        $(document).ready(function () {
            dataTable =  $("#customerTable").DataTable({
                "ajax": {
                    "url": "/Customer/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                
                "columns": [
                    { "data": "ClietId" },
                    { "data": "CustomerName" },
                    { "data": "Address" },
                    { "data": "Email" },
                    { "data": "Contact" },
                    { "data": "LoyaltyPoint" },
                    { "data": "ImagePath" },
                    {"data":"ClietId" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit","Customer")/" + data + "')><i class='fa fa-pencil'></i> Edit</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fa fa-trash'></i> Delete</a>";
                    },
                        "orderable": false,
                        "searchable":false,
                        "width":"150px"
                    }

                ],
                "language": {

                    "emptyTable" : "No data found, Please click on <b>Add New</b> Button"
                }
            });
        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response);

                Popup = formDiv.dialog({
                    autoOpen: true,
                    resizable: false,
                    title: 'Fill Customer Details',
                    height: 500,
                    width: 700,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }

                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if($(form).valid()){
                $.ajax({
                    type : "POST",
                    url : form.action,
                    data : $(form).serialize(),
                    success : function (data) {
                        if(data.success)
                        {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message,{
                                globalPosition :"top center",
                                className : "success"
                            })

                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            if(confirm('Are You Sure to Delete this Customer Record ?'))
            {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","Product")/' + id,
                    success: function (data) {
                        if (data.success)
                        {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }

                });
            }
        }
    </script>
}